---
- name: Установка и настройка Apache
  hosts: your_server_ip
  become: yes
  tasks:
    - name: Обновить список пакетов
      apt:
        update_cache: yes

    - name: Установить Apache
      apt:
        name: apache2
        state: present

    - name: Запустить Apache и добавить в автозагрузку
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Создать каталог для веб-сайта
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data

    - name: Создать тестовую веб-страницу
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data

    - name: Разрешить доступ к порту 80
      ufw:
        rule: allow
        port: 80
        proto: tcp

